### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by ebergstr** [lemire/fastrand#11]
Is there a way to set our own seed for reproducibility purposes? Similarly for ensuring different streams while parallelizing code...

**Comment by lemire** [comment]
Have you tried, for example, `pcg32_seed`?

**Comment by ebergstr** [comment]
That does not appear to be an available module:

AttributeError: module 'fastrand' has no attribute 'pcg32_seed'

EDIT:
I realized the package has been updated since I downloaded it. The module is now present, however, i get a "Segmentation fault" when attempting to pass my own seed.

**Comment by lemire** [comment]
Yes. This should be fixed in version 1.2. Can you check? If not available now, it should soon be available.

**Comment by lemire** [comment]
https://pypi.org/project/fastrand/

**Comment by ebergstr** [comment]
It appears to be working now, thanks!
