### ISSUE TITLE
"pip install fastrand" prefers to install version1.1 instead of 1.2

### ISSUE THREAD

**Issue by burcakotlu** [lemire/fastrand#12]
Hi to all,

We tried to download latest version of fastrand 1.2. 
However "pip install fastrand" ended up installing 1.1
"pip install fastrand --upgrade" also ended up installing 1.1
What can be the reason for that?

Best,
Burcak Otlu

**Comment by lemire** [comment]
Please try again and report your platform if it fails.

We only support the following wheels...
https://pypi.org/project/fastrand/#files

If you have a different platform, you should be installing from source... 

Closing... reopen if you have more details.

**Comment by lemire** [comment]
You may also try
```
pip install fastrand==1.2.4
```
