### ISSUE TITLE
Should the result of pcg32() be signed?

### ISSUE THREAD

**Issue by jnrbsn** [lemire/fastrand#14]
The C function `pcg32_random()` returns an _unsigned_ `uint32_t`, but the `pcg32()` function exposed to Python calls `Py_BuildValue()` with `"i"`, which causes it to return a _signed_ `int` ([docs](https://docs.python.org/3/c-api/arg.html#numbers)). Is this a bug or was it intentional? I don't see this explicitly mentioned anywhere, but I assumed it would give me unsigned 32-bit integers, and I was surprised to see it giving me negative numbers.

**Comment by lemire** [comment]
You are correct, it should not be.

**Comment by lemire** [comment]
Fixed in a commit.

**Comment by jnrbsn** [comment]
It looks like you published a new version to PyPI (1.3.0), but the only [available downloads](https://pypi.org/project/fastrand/1.3.0/#files) are for Windows. So it won't let me install it on macOS or Linux. [Previous versions](https://pypi.org/project/fastrand/1.2.4/#files) had a source distribution available that would get used on macOS and Linux.

**Comment by lemire** [comment]
Right. Should be good now. Please check.

(It used to be automatic but travis is botching it.)

**Comment by jnrbsn** [comment]
I can install it now, and I can confirm it's no longer giving me negative integers. Thanks.

**Comment by lemire** [comment]
Thanks for the feedback. Hopefully this will prove useful.
