### ISSUE TITLE
Enhancment: Add option for bounded randoms such randint in numpy and python.random

### ISSUE THREAD

**Issue by ndragon798** [lemire/fastrand#15]
Add an option to specify a lower bound for the random int generation.
Examples from numpy and the random lib in python below.

`numpy.random.randint(950, 1000)`
`random.randint(100,1000)`

This would make fastrand a better replacement for quickly generating random ints.

**Comment by lemire** [comment]
Pull request invited !

**Comment by lemire** [comment]
Should be fixed in release 1.8.0
