### ISSUE TITLE
How to Guess Upper/Lower bound of a fastrand ? 

### ISSUE THREAD

**Issue by Sim4n6** [lemire/fastrand#16]
Hi, 

I'm a little novice, who would like to solve the following little problem:

1. Say I can control when to generate a number using `fastrand` (bounded for instance by 1001).
2. How can I guess at best its interval? 

I mean: 
 1. suppose now, fastrand generate the number 989.
 2. is there a way to figure out a lower/upper bound, such as 900 to 1000, please?

Regards,

**Comment by lemire** [comment]
It is unclear what you mean. Can you elaborate ?

**Comment by Sim4n6** [comment]
If I generate fast rand 5min ago, can we guess its value (up, low interval) please?

**Comment by lemire** [comment]
No. You cannot.

**Comment by Sim4n6** [comment]
thank u
