### ISSUE TITLE
Python3 installation

### ISSUE THREAD

**Issue by GPaolo** [lemire/fastrand#7]
When installing for Python3.5, at import time it gives an error:

> undefined symbol: PyInt_AsUnsignedLongLongMask

to solve it, I had to modify the .c file from:

#if PY_MAJOR_VERSION >= 3
#define PyInt_AsLong(x)   PyLong_AsLong(x)
#endif

to 

#if PY_MAJOR_VERSION >= 3
#define PyInt_AsLong(x)   PyLong_AsLong(x)
#define PyInt_AsUnsignedLongLongMask(x) PyLong_AsUnsignedLongLongMask(x)
#endif

**Comment by lemire** [comment]
Do you want to issue this as a pull request?

One immediate benefit is that you get credit for your work.

**Comment by GPaolo** [comment]
Sure. Doing it.
